import Header from "./components/header/Header";
import "./globals.css";

export const metadata = {
  title: "4Peice Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
